### ISSUE TITLE
cant pull galaxy docker container latest tag

### ISSUE THREAD

**Issue by eimarfandino** [otaviof/galaxy#1]
i cant manage to pull galaxy docker container latest tag.

steps to reproduce:
``` bash
⤷ docker pull otaviof/galaxy:latest
Error response from daemon: manifest for otaviof/galaxy:latest not found
```
extra info: 
version 0.0.2  works

**Comment by otaviof** [comment]
I'm checking the Docker-Hub build settings to see if `latest` is configured to be tagged. On that build configuration, it's using the git tag as container tag, and every time a new version tag is created, it's also tagging the new container as `latest`.

Therefore, by checking that's going to happen in `0.0.3` we gonna make sure it's working as intended. :-)

**Comment by eimarfandino** [comment]
@otaviof i can pull version `0.0.3` but not `latest`

**Comment by otaviof** [comment]
@eimarfandino I may have to open a ticket/case in DockerHub upstream, since on managing the repository we have the following:

<img width="661" alt="docker-hub screenshot" src="https://user-images.githubusercontent.com/11710/59914858-9b2dab00-941b-11e9-8926-9ba310f74ba4.png">

**Comment by eimarfandino** [comment]
resolved @otaviof
