### ISSUE TITLE
binary is not called galaxy but vault-helper

### ISSUE THREAD

**Issue by eimarfandino** [otaviof/galaxy#2]
the binaries uploaded on https://github.com/otaviof/galaxy/releases are called `vault-helper` instead of `galaxy`

next to this seems it can't be executed? 
``` bash
⤷ ./vault-handler
zsh: exec format error: ./vault-handler
```

**Comment by otaviof** [comment]
Indeed, good catch! That should be fixed now, could you confirm over `0.0.3`?

**Comment by eimarfandino** [comment]
@otaviof confirmed. just one thingy, when i try to run the binary i get 
```
⤷ ./galaxy
zsh: exec format error: ./galaxy
```

Do you know why?

**Comment by otaviof** [comment]
@eimarfandino try the following:
```
$ make
$ ./build/galaxy
```

When you get a `exec format error` means the binary is not ready for the OS you're trying to run it.

**Comment by eimarfandino** [comment]
ah check. might be nice if instead of just linux also darwin is released, for macbooks. I'll consider this issue close
